# https://taskfile.dev/docs/guide
version: "3"

vars:
    BUILD_DIR: build
    LLAMA_SERVER: "{{.BUILD_DIR}}/bin/llama-server"
    LLAMA_SERVER_COMMON_ARGS: >-
        --host 0.0.0.0
        --ctx-size 8192
        --gpu-layers all
        --jinja

tasks:
    release:configure:
        desc: "Configure release build"
        vars:
            cmake_args: >-
                -G Ninja
                -S llama.cpp
                -B {{.BUILD_DIR}}
                -DCMAKE_BUILD_TYPE=Release
                -DCMAKE_C_COMPILER="/usr/bin/clang"
                -DCMAKE_CXX_COMPILER="/usr/bin/clang++"
                -DCMAKE_C_COMPILER_LAUNCHER="ccache"
                -DCMAKE_CXX_COMPILER_LAUNCHER="ccache"
                -DCMAKE_OSX_ARCHITECTURES=arm64
                -DGGML_METAL=ON
                -DGGML_NATIVE=ON
                -DBUILD_SHARED_LIBS=OFF
        cmd: cmake {{.cmake_args}}

    release:build:
        desc: "Build release"
        cmd: cmake --build {{.BUILD_DIR}}

    release:clean:
        desc: "Clean release build"
        cmd: cmake --build {{.BUILD_DIR}} --target clean

    server:hf:
        internal: true
        requires:
            vars:
                - HF_REPO
                - ALIAS
                - PORT
        cmd: >-
            {{.LLAMA_SERVER}}
            -hf {{.HF_REPO}}
            --alias {{.ALIAS}}
            --port {{.PORT}}
            {{.LLAMA_SERVER_COMMON_ARGS}}

    server:lfm25-jp:
        desc: "Run LFM2.5 1.2B JP server"
        cmds:
            - task: server:hf
              vars:
                  HF_REPO: LiquidAI/LFM2.5-1.2B-JP-202606-GGUF:Q4_K_M
                  ALIAS: lfm25-12b-jp-202606-q4
                  PORT: 8082

    open-web-ui:up:
        desc: "Run Open Web UI in foreground"
        cmd: docker compose up open-web-ui

    open-web-ui:up:detach:
        desc: "Run Open Web UI in background"
        cmd: docker compose up -d open-web-ui

    open-web-ui:down:
        desc: "Stop Open Web UI"
        cmd: docker compose down

    open-web-ui:logs:
        desc: "Show Open Web UI logs"
        cmd: docker compose logs -f open-web-ui

    open-web-ui:pull:
        desc: "Pull Open Web UI image"
        cmd: docker compose pull open-web-ui
